### PR TITLE
add by ram 1 file

### PR DESCRIPTION
**Pull request by rambn1234**
hi sam i did this task please check and approve.

### CODE REVIEW

**Comment by sameers718** [comment]
Hi ram,

add one more line in your class

Thanks and regards
Sameer

**Comment by rambn1234** [comment]
add line please approve

**Comment by sameers718** [comment]
Okk looks cool all good go for the merge

**Comment by rambn1234** [comment]
added one more file now  file name R.

**Comment by sameers718** [comment]
Okk go for the merge

**Pull request merged**
